service: crud-cars-credits
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    DYNAMODB_TABLE: cars_credits_${self:provider.stage}
    
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
      Resource:
        - arn:aws:dynamodb:us-east-1:929989973262:table/cars_credits_${self:provider.stage}

functions:
  createCredit:
    handler: src/createCredit.handler
    events:
      - httpApi:
          path: /new_credit
          method: post
          

  getCredit:
    handler: src/getCredit.handler
    events:
      - httpApi:
          path: /get_credit/{id}
          method: get

  updateCredit:
    handler: src/updateCredit.handler
    events:
      - httpApi:
          path: /update_credit/{id}
          method: put

  deleteCredit:
    handler: src/deleteCredit.handler
    events:
      - httpApi:
          path: /delete_credit/{id}
          method: delete

  getCreditById:
    handler: src/getCreditById.handler
    events:
      - httpApi:
          path: /credits/{id}
          method: get

resources:
  Resources:
    CreditosAutosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cars_credits_${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: idClient
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: IdClientIndex
            KeySchema:
              - AttributeName: idClient
                KeyType: HASH
            Projection:
              ProjectionType: ALL
