service: crud-cars-credits
frameworkVersion: '4'

package:
  individually: true
  exclude:
    - "test/**"
    - ".vscode/**"
    - ".git/**"
    - "*.png"
    - "*.jpg"
    - "README.md"

provider:
  name: aws
  runtime: nodejs20.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    DYNAMODB_TABLE: cars_credits_${self:provider.stage}
    
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
      Resource:
        - arn:aws:dynamodb:us-east-1:929989973262:table/cars_credits_${self:provider.stage}

functions:
  createCredit:
    handler: src/interfaces/handlers/createCreditHandler.handler
    events:
      - httpApi:
          path: /new_credit
          method: post
          

  getCreditById:
    handler: src/interfaces/handlers/getCreditByIdHandler.handler
    events:
      - httpApi:
          path: /get_credit/{id}
          method: get

  getAllCredits:
    handler: src/interfaces/handlers/getAllCreditsHandler.handler
    events:
      - httpApi:
          path: /get_allcredits
          method: get

  updateCredit:
    handler: src/interfaces/handlers/updateCreditHandler.handler
    events:
      - httpApi:
          path: /update_credit
          method: put

  deleteCredit:
    handler: src/interfaces/handlers/deleteCreditHandler.handler
    events:
      - httpApi:
          path: /delete_credit/{id}
          method: delete

  getCreditsByIdClient:
    handler: src/interfaces/handlers/getCreditsByClientIdHandler.handler
    events:
      - httpApi:
          path:  /client/{idClient}/credits
          method: get

resources:
  Resources:
    CreditosAutosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cars_credits_${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: idClient
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: IdClientIndex
            KeySchema:
              - AttributeName: idClient
                KeyType: HASH
            Projection:
              ProjectionType: ALL

build:
  esbuild:
    bundle: true
    minify: false
    exclude: ['aws-sdk']
    target: 'node20'
    platform: 'node'


